version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./web_data:/app/web_data
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./web_data/storage:/data/db
    networks:
      - backend

networks:
  backend: